export const categories = [
  { 
    name: "Mobiles", 
    icon: "📱", 
    id: "mobiles", 
    image_url: "/products/iphone-16-pro-max.png",
    sub_categories: ["Flagship Phones", "5G Phones", "Gaming Phones", "Budget Phones"]
  },
  { 
    name: "Old / Refurbished Mobiles", 
    icon: "♻️", 
    id: "old-refurbished-mobiles", 
    image_url: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&q=80&w=600",
    sub_categories: ["Superb Grade A+", "Like New", "Refurbished iPhones", "Refurbished Android"]
  },
  { 
    name: "Mobile Accessories", 
    icon: "🔌", 
    id: "mobile-accessories", 
    image_url: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=600",
    sub_categories: ["Chargers & Adapters", "Cases & Covers", "Tempered Glass", "Power Banks", "Cables"]
  },
  { 
    name: "Fashion", 
    icon: "👜", 
    id: "fashion", 
    image_url: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&q=80&w=600",
    sub_categories: ["Handbags & Purses", "Watches & Chronographs", "Fashion Accessories", "Apparel & Bags"]
  },
  { 
    name: "Jewellery", 
    icon: "💍", 
    id: "jewellery", 
    image_url: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=80&w=600",
    sub_categories: ["Gold & Diamond Jewellery", "Silver & Moissanite", "Necklace Sets & Chokers", "Rings & Bangles"]
  },
  { 
    name: "EV Vehicles", 
    icon: "⚡", 
    id: "ev-vehicles", 
    image_url: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&q=80&w=600",
    sub_categories: ["Electric Scooters", "Electric Bikes", "EV Accessories & Chargers"]
  },
  { 
    name: "Computers & Tablets", 
    icon: "💻", 
    id: "computers-tablets", 
    image_url: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&q=80&w=600",
    sub_categories: ["Laptops", "iPads & Tablets", "Gaming Laptops", "Monitors & Storage"]
  },
  { 
    name: "TV & Audio", 
    icon: "📺", 
    id: "tv-audio", 
    image_url: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&q=80&w=600",
    sub_categories: ["4K Smart TVs", "Soundbars & Speakers", "Noise Canceling Headphones", "Home Theatres"]
  },
  { 
    name: "Kitchen Appliances", 
    icon: "🍳", 
    id: "kitchen-appliances", 
    image_url: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=600",
    sub_categories: ["Mixer Grinders", "Air Fryers", "Wet Grinders", "Microwave Ovens"]
  },
  { 
    name: "Home Appliances", 
    icon: "🏠", 
    id: "home-appliances", 
    image_url: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600",
    sub_categories: ["Refrigerators", "Washing Machines", "Air Conditioners", "Water Purifiers"]
  },
  { 
    name: "Smart Technology", 
    icon: "💡", 
    id: "smart-technology", 
    image_url: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&q=80&w=600",
    sub_categories: ["Smartwatches", "Smart Home Cameras", "Smart Lighting", "Fitness Trackers"]
  }
];

export const trendingMobileSubCategories = [
  {
    name: "Mobile",
    image: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&q=80&w=400",
    sub: "Mobile"
  },
  {
    name: "Chargers",
    image: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=400",
    sub: "Chargers"
  },
  {
    name: "Storage",
    image: "https://images.unsplash.com/photo-1628155930542-3c7a64e2c833?auto=format&fit=crop&q=80&w=400",
    sub: "Storage"
  },
  {
    name: "Adapters",
    image: "https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&q=80&w=400",
    sub: "Adapters"
  },
  {
    name: "Tempered Glass",
    image: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?auto=format&fit=crop&q=80&w=400",
    sub: "Tempered Glass"
  },
  {
    name: "Power Bank",
    image: "https://images.unsplash.com/photo-1609592424357-6c243859600e?auto=format&fit=crop&q=80&w=400",
    sub: "Power Bank"
  },
  {
    name: "Case & Covers",
    image: "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&q=80&w=400",
    sub: "Case & Covers"
  }
];

export const products = [
  // ==================== 1. BRAND NEW MOBILES ====================
  {
    id: "samsung-galaxy-z-fold7",
    category: "Mobiles",
    category_id: "mobiles",
    sub_category: "Flagship Phones",
    name: "Samsung Galaxy Z Fold7 5G Mobile with Galaxy AI (Silver Shadow, 12GB RAM, 256GB Storage), Ultra Sleek Design with 200MP Camera, Ultra-Smooth Gaming with Powerful Snapdragon 8 Elite, Google Gemini",
    unit: "12GB RAM | 256GB ROM • Snapdragon 8 Elite • 200MP AI Pro Camera",
    price: 174999,
    original_price: 204999,
    stock_quantity: 24,
    cashback_amount: 5249,
    warranty_period: "1 Year Official Samsung Brand Warranty",
    condition: "Brand New Sealed",
    image_url: "/products/samsung-galaxy-z-fold7.jpg",
    images: [
      "/products/samsung-galaxy-z-fold7.jpg",
      "/products/samsung-galaxy-s26-ultra.jpg",
      "/products/samsung-galaxy-s25-ultra.png"
    ],
    is_available: true,
    is_popular: true,
    is_featured: true,
    rating: 4.5,
    reviews_count: 111,
    description: "Samsung Galaxy Z Fold7 5G with Galaxy AI, Titanium hinge architecture, Ultra Sleek foldable Dynamic AMOLED 2X 120Hz display, 200MP AI Quad camera, Snapdragon 8 Elite high-performance processor, and Google Gemini deep assistant integration.",
    variants: [
      {
        id: "zfold7_12_256_silver",
        ram: "12GB",
        rom: "256GB",
        storage_label: "12GB RAM + 256GB ROM",
        color: "Silver Shadow",
        color_code: "#c0c0c0",
        price: 174999,
        original_price: 204999,
        stock_quantity: 14,
        sku: "ZFOLD7-12-256-SILVER",
        image_url: "/products/samsung-galaxy-z-fold7.jpg",
        is_active: true
      },
      {
        id: "zfold7_12_512_black",
        ram: "12GB",
        rom: "512GB",
        storage_label: "12GB RAM + 512GB ROM",
        color: "Phantom Black",
        color_code: "#18181b",
        price: 189999,
        original_price: 219999,
        stock_quantity: 10,
        sku: "ZFOLD7-12-512-BLACK",
        image_url: "/products/samsung-galaxy-z-fold7.jpg",
        is_active: true
      }
    ]
  },
  {
    id: "oneplus-ce6-lite",
    category: "Mobiles",
    category_id: "mobiles",
    sub_category: "5G Phones",
    name: "OnePlus Nord CE6 Lite 5G (Super Silver, 8GB RAM, 128GB Storage) | 7000mAh Massive Battery | 1.03Mn+ AnTuTu | OxygenOS 15",
    unit: "8GB RAM | 128GB ROM • 7000mAh Battery • 120Hz AMOLED • 50MP Sony LYT",
    price: 26999,
    original_price: 33999,
    stock_quantity: 45,
    cashback_amount: 1500,
    warranty_period: "1 Year Official OnePlus Warranty",
    condition: "Brand New Sealed",
    image_url: "/products/oneplus-nord-6-lite.jpg",
    images: [
      "/products/oneplus-nord-6-lite.jpg",
      "/products/google-pixel-9-pro-xl.png"
    ],
    is_available: true,
    is_popular: true,
    is_featured: true,
    rating: 4.4,
    reviews_count: 3829,
    description: "OnePlus Nord CE6 Lite 5G delivers unstoppable battery stamina with a 7000mAh battery, ultra-smooth 120Hz AMOLED display, 50MP Sony LYT primary camera with OIS, and blazingly fast OxygenOS 15.",
    variants: [
      {
        id: "ce6_8_128_silver",
        ram: "8GB",
        rom: "128GB",
        storage_label: "8GB RAM + 128GB ROM",
        color: "Super Silver",
        color_code: "#cbd5e1",
        price: 26999,
        original_price: 33999,
        stock_quantity: 25,
        sku: "CE6-8-128-SILVER",
        image_url: "/products/oneplus-nord-6-lite.jpg",
        is_active: true
      },
      {
        id: "ce6_8_256_blue",
        ram: "8GB",
        rom: "256GB",
        storage_label: "8GB RAM + 256GB ROM",
        color: "Mega Blue",
        color_code: "#0284c7",
        price: 29999,
        original_price: 36999,
        stock_quantity: 20,
        sku: "CE6-8-256-BLUE",
        image_url: "/products/oneplus-nord-6-lite.jpg",
        is_active: true
      }
    ]
  },
  {
    id: "samsung-s26-ultra",
    category: "Mobiles",
    category_id: "mobiles-accessories",
    sub_category: "Flagship Phones",
    name: "Samsung Galaxy S26 Ultra 5G (Titanium Silver, 512 GB, 16 GB RAM)",
    unit: "16GB RAM | 512GB ROM • Snapdragon 8 Elite Gen 2 • 200MP Quad Pro AI",
    price: 139999,
    original_price: 149999,
    stock_quantity: 36,
    cashback_amount: 5000,
    warranty_period: "1 Year Official Samsung Warranty",
    condition: "Brand New Sealed",
    image_url: "/products/samsung-galaxy-s26-ultra.jpg",
    images: [
      "/products/samsung-galaxy-s26-ultra.jpg",
      "/hero/samsung-s26-ultra-ad.jpg"
    ],
    is_available: true,
    is_popular: true,
    rating: 5.0,
    reviews_count: 2450,
    description: "The pinnacle of flagship performance with Next-Gen Galaxy AI. Powered by Snapdragon 8 Elite, ultra-bright 6.9-inch Dynamic AMOLED 2X with Gorilla Armor 2, upgraded 200MP Quad Pro AI camera with 150x Space Zoom, built-in S-Pen, Grade 5 Titanium frame, 6000mAh battery with 65W Super Fast Charging.",
    variants: [
      {
        id: "s26u_12_256_silver",
        ram: "12GB",
        rom: "256GB",
        storage_label: "12GB RAM + 256GB ROM",
        color: "Titanium Silver",
        color_code: "#c0c0c0",
        price: 129999,
        original_price: 139999,
        stock_quantity: 12,
        sku: "S26U-12-256-SILVER",
        image_url: "/products/samsung-galaxy-s26-ultra.jpg",
        is_active: true
      },
      {
        id: "s26u_12_256_black",
        ram: "12GB",
        rom: "256GB",
        storage_label: "12GB RAM + 256GB ROM",
        color: "Titanium Black",
        color_code: "#1f2428",
        price: 129999,
        original_price: 139999,
        stock_quantity: 8,
        sku: "S26U-12-256-BLACK",
        image_url: "/products/samsung-galaxy-s25-ultra.png",
        is_active: true
      },
      {
        id: "s26u_12_256_violet",
        ram: "12GB",
        rom: "256GB",
        storage_label: "12GB RAM + 256GB ROM",
        color: "Cobalt Violet",
        color_code: "#58427c",
        price: 129999,
        original_price: 139999,
        stock_quantity: 0,
        sku: "S26U-12-256-VIOLET",
        image_url: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&q=80&w=600",
        is_active: true
      },
      {
        id: "s26u_16_512_silver",
        ram: "16GB",
        rom: "512GB",
        storage_label: "16GB RAM + 512GB ROM",
        color: "Titanium Silver",
        color_code: "#c0c0c0",
        price: 139999,
        original_price: 149999,
        stock_quantity: 15,
        sku: "S26U-16-512-SILVER",
        image_url: "/products/samsung-galaxy-s26-ultra.jpg",
        is_active: true
      },
      {
        id: "s26u_16_512_black",
        ram: "16GB",
        rom: "512GB",
        storage_label: "16GB RAM + 512GB ROM",
        color: "Titanium Black",
        color_code: "#1f2428",
        price: 139999,
        original_price: 149999,
        stock_quantity: 2,
        sku: "S26U-16-512-BLACK",
        image_url: "/products/samsung-galaxy-s25-ultra.png",
        is_active: true
      },
      {
        id: "s26u_16_512_gold",
        ram: "16GB",
        rom: "512GB",
        storage_label: "16GB RAM + 512GB ROM",
        color: "Amber Gold",
        color_code: "#e5a93c",
        price: 139999,
        original_price: 149999,
        stock_quantity: 4,
        sku: "S26U-16-512-GOLD",
        image_url: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&q=80&w=600",
        is_active: true
      },
      {
        id: "s26u_16_512_violet",
        ram: "16GB",
        rom: "512GB",
        storage_label: "16GB RAM + 512GB ROM",
        color: "Cobalt Violet",
        color_code: "#58427c",
        price: 139999,
        original_price: 149999,
        stock_quantity: 0,
        sku: "S26U-16-512-VIOLET",
        image_url: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&q=80&w=600",
        is_active: true
      },
      {
        id: "s26u_16_1tb_silver",
        ram: "16GB",
        rom: "1TB",
        storage_label: "16GB RAM + 1TB ROM",
        color: "Titanium Silver",
        color_code: "#c0c0c0",
        price: 159999,
        original_price: 169999,
        stock_quantity: 3,
        sku: "S26U-16-1TB-SILVER",
        image_url: "/products/samsung-galaxy-s26-ultra.jpg",
        is_active: true
      },
      {
        id: "s26u_16_1tb_black",
        ram: "16GB",
        rom: "1TB",
        storage_label: "16GB RAM + 1TB ROM",
        color: "Titanium Black",
        color_code: "#1f2428",
        price: 159999,
        original_price: 169999,
        stock_quantity: 0,
        sku: "S26U-16-1TB-BLACK",
        image_url: "/products/samsung-galaxy-s25-ultra.png",
        is_active: true
      }
    ]
  },
  {
    id: "iphone-16-pro-max",
    category: "Mobiles",
    category_id: "mobiles-accessories",
    sub_category: "Flagship Phones",
    name: "Apple iPhone 16 Pro Max (Desert Titanium, 256 GB)",
    unit: "256GB / 512GB / 1TB • A18 Pro Chip • 6.9\" Super Retina XDR",
    price: 139999,
    original_price: 144900,
    stock_quantity: 49,
    cashback_amount: 4000,
    warranty_period: "1 Year Official Apple India Warranty",
    condition: "Brand New Sealed",
    image_url: "/products/iphone-16-pro-max.png",
    images: [
      "/products/iphone-16-pro-max.png"
    ],
    is_available: true,
    is_popular: true,
    rating: 4.9,
    reviews_count: 1420,
    description: "Built for Apple Intelligence. 6.9-inch Super Retina XDR display with ProMotion 120Hz, A18 Pro chip with 6-core GPU, 48MP Fusion Camera Control button, and Grade 5 Titanium architecture with official 1-Year Apple India warranty.",
    variants: [
      {
        id: "ip16pm_256_desert",
        ram: "8GB",
        rom: "256GB",
        storage_label: "8GB RAM + 256GB ROM",
        color: "Desert Titanium",
        color_code: "#c5a582",
        price: 139999,
        original_price: 144900,
        stock_quantity: 18,
        sku: "IP16PM-256-DESERT",
        image_url: "/products/iphone-16-pro-max.png",
        is_active: true
      },
      {
        id: "ip16pm_256_natural",
        ram: "8GB",
        rom: "256GB",
        storage_label: "8GB RAM + 256GB ROM",
        color: "Natural Titanium",
        color_code: "#9e9893",
        price: 134999,
        original_price: 144900,
        stock_quantity: 9,
        sku: "IP16PM-256-NATURAL",
        image_url: "/products/iphone-16-pro-max.png",
        is_active: true
      },
      {
        id: "ip16pm_256_white",
        ram: "8GB",
        rom: "256GB",
        storage_label: "8GB RAM + 256GB ROM",
        color: "White Titanium",
        color_code: "#f2f2f0",
        price: 137499,
        original_price: 144900,
        stock_quantity: 4,
        sku: "IP16PM-256-WHITE",
        image_url: "/products/iphone-16-pro-max.png",
        is_active: true
      },
      {
        id: "ip16pm_256_black",
        ram: "8GB",
        rom: "256GB",
        storage_label: "8GB RAM + 256GB ROM",
        color: "Black Titanium",
        color_code: "#2a2b2e",
        price: 131999,
        original_price: 144900,
        stock_quantity: 5,
        sku: "IP16PM-256-BLACK",
        image_url: "/products/iphone-16-pro-max.png",
        is_active: true
      },
      {
        id: "ip16pm_512_desert",
        ram: "8GB",
        rom: "512GB",
        storage_label: "8GB RAM + 512GB ROM",
        color: "Desert Titanium",
        color_code: "#c5a582",
        price: 159999,
        original_price: 164900,
        stock_quantity: 10,
        sku: "IP16PM-512-DESERT",
        image_url: "/products/iphone-16-pro-max.png",
        is_active: true
      },
      {
        id: "ip16pm_512_natural",
        ram: "8GB",
        rom: "512GB",
        storage_label: "8GB RAM + 512GB ROM",
        color: "Natural Titanium",
        color_code: "#9e9893",
        price: 154999,
        original_price: 164900,
        stock_quantity: 6,
        sku: "IP16PM-512-NATURAL",
        image_url: "/products/iphone-16-pro-max.png",
        is_active: true
      },
      {
        id: "ip16pm_512_black",
        ram: "8GB",
        rom: "512GB",
        storage_label: "8GB RAM + 512GB ROM",
        color: "Black Titanium",
        color_code: "#2a2b2e",
        price: 151999,
        original_price: 164900,
        stock_quantity: 3,
        sku: "IP16PM-512-BLACK",
        image_url: "/products/iphone-16-pro-max.png",
        is_active: true
      },
      {
        id: "ip16pm_1tb_desert",
        ram: "8GB",
        rom: "1TB",
        storage_label: "8GB RAM + 1TB ROM",
        color: "Desert Titanium",
        color_code: "#c5a582",
        price: 179999,
        original_price: 184900,
        stock_quantity: 4,
        sku: "IP16PM-1TB-DESERT",
        image_url: "/products/iphone-16-pro-max.png",
        is_active: true
      },
      {
        id: "ip16pm_1tb_black",
        ram: "8GB",
        rom: "1TB",
        storage_label: "8GB RAM + 1TB ROM",
        color: "Black Titanium",
        color_code: "#2a2b2e",
        price: 172999,
        original_price: 184900,
        stock_quantity: 2,
        sku: "IP16PM-1TB-BLACK",
        image_url: "/products/iphone-16-pro-max.png",
        is_active: true
      }
    ]
  },
  {
    id: "samsung-s25-ultra",
    category: "Mobiles",
    category_id: "mobiles-accessories",
    sub_category: "Flagship Phones",
    name: "Samsung Galaxy S25 Ultra 5G (Titanium Silverblue, 256 GB, 12 GB RAM)",
    unit: "12GB RAM | 256GB ROM • Snapdragon 8 Elite • 200MP Quad AI",
    price: 129999,
    original_price: 139999,
    stock_quantity: 26,
    cashback_amount: 3500,
    warranty_period: "1 Year Official Samsung Warranty",
    condition: "Brand New Sealed",
    image_url: "/products/samsung-galaxy-s25-ultra.png",
    is_available: true,
    is_popular: true,
    rating: 4.9,
    reviews_count: 1120,
    description: "The ultimate Android flagship with Galaxy AI. Snapdragon 8 Elite for Galaxy, 200MP Quad AI camera with 100x Space Zoom, Anti-Reflective Gorilla Armor glass, Titanium chassis, and built-in S-Pen.",
    variants: [
      {
        id: "s25u_12_256_silverblue",
        ram: "12GB",
        rom: "256GB",
        storage_label: "12GB RAM + 256GB ROM",
        color: "Titanium Silverblue",
        color_code: "#8fa3b8",
        price: 129999,
        original_price: 139999,
        stock_quantity: 15,
        sku: "S25U-12-256-SBLUE",
        image_url: "/products/samsung-galaxy-s25-ultra.png",
        is_active: true
      },
      {
        id: "s25u_12_256_gray",
        ram: "12GB",
        rom: "256GB",
        storage_label: "12GB RAM + 256GB ROM",
        color: "Titanium Gray",
        color_code: "#6b7280",
        price: 129999,
        original_price: 139999,
        stock_quantity: 0,
        sku: "S25U-12-256-GRAY",
        image_url: "/products/samsung-galaxy-s25-ultra.png",
        is_active: true
      },
      {
        id: "s25u_12_512_silverblue",
        ram: "12GB",
        rom: "512GB",
        storage_label: "12GB RAM + 512GB ROM",
        color: "Titanium Silverblue",
        color_code: "#8fa3b8",
        price: 139999,
        original_price: 149999,
        stock_quantity: 8,
        sku: "S25U-12-512-SBLUE",
        image_url: "/products/samsung-galaxy-s25-ultra.png",
        is_active: true
      },
      {
        id: "s25u_12_512_gray",
        ram: "12GB",
        rom: "512GB",
        storage_label: "12GB RAM + 512GB ROM",
        color: "Titanium Gray",
        color_code: "#6b7280",
        price: 139999,
        original_price: 149999,
        stock_quantity: 3,
        sku: "S25U-12-512-GRAY",
        image_url: "/products/samsung-galaxy-s25-ultra.png",
        is_active: true
      }
    ]
  },
  {
    id: "oneplus-13",
    category: "Mobiles",
    category_id: "mobiles-accessories",
    sub_category: "5G Phones",
    name: "OnePlus 13 5G (Midnight Ocean, 512 GB, 16 GB RAM)",
    unit: "16GB RAM | 512GB ROM • Snapdragon 8 Elite • 6000mAh 100W",
    price: 69999,
    original_price: 74999,
    stock_quantity: 34,
    cashback_amount: 2000,
    warranty_period: "1 Year Official OnePlus Warranty",
    condition: "Brand New Sealed",
    image_url: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.9,
    reviews_count: 890,
    description: "Snapdragon 8 Elite Processor, 2K 120Hz Oriental OLED Display, 50MP Hasselblad Triple Camera with Sony LYT-808, 6000mAh Glacier Battery with 100W SUPERVOOC + 50W AIRVOOC, and IP69 water rating.",
    variants: [
      {
        id: "op13_12_256_midnight",
        ram: "12GB",
        rom: "256GB",
        storage_label: "12GB RAM + 256GB ROM",
        color: "Midnight Ocean",
        color_code: "#1a2c3a",
        price: 64999,
        original_price: 69999,
        stock_quantity: 14,
        sku: "OP13-12-256-MIDNIGHT",
        image_url: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&q=80&w=600",
        is_active: true
      },
      {
        id: "op13_12_256_white",
        ram: "12GB",
        rom: "256GB",
        storage_label: "12GB RAM + 256GB ROM",
        color: "Arctic Dawn White",
        color_code: "#e6eaed",
        price: 64999,
        original_price: 69999,
        stock_quantity: 0,
        sku: "OP13-12-256-WHITE",
        image_url: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&q=80&w=600",
        is_active: true
      },
      {
        id: "op13_12_256_emerald",
        ram: "12GB",
        rom: "256GB",
        storage_label: "12GB RAM + 256GB ROM",
        color: "Emerald Green",
        color_code: "#2a5c4d",
        price: 64999,
        original_price: 69999,
        stock_quantity: 6,
        sku: "OP13-12-256-EMERALD",
        image_url: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&q=80&w=600",
        is_active: true
      },
      {
        id: "op13_16_512_midnight",
        ram: "16GB",
        rom: "512GB",
        storage_label: "16GB RAM + 512GB ROM",
        color: "Midnight Ocean",
        color_code: "#1a2c3a",
        price: 69999,
        original_price: 74999,
        stock_quantity: 10,
        sku: "OP13-16-512-MIDNIGHT",
        image_url: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&q=80&w=600",
        is_active: true
      },
      {
        id: "op13_16_512_white",
        ram: "16GB",
        rom: "512GB",
        storage_label: "16GB RAM + 512GB ROM",
        color: "Arctic Dawn White",
        color_code: "#e6eaed",
        price: 69999,
        original_price: 74999,
        stock_quantity: 4,
        sku: "OP13-16-512-WHITE",
        image_url: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&q=80&w=600",
        is_active: true
      },
      {
        id: "op13_16_512_emerald",
        ram: "16GB",
        rom: "512GB",
        storage_label: "16GB RAM + 512GB ROM",
        color: "Emerald Green",
        color_code: "#2a5c4d",
        price: 69999,
        original_price: 74999,
        stock_quantity: 0,
        sku: "OP13-16-512-EMERALD",
        image_url: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&q=80&w=600",
        is_active: true
      }
    ]
  },
  {
    id: "pixel-9-pro-xl",
    category: "Mobiles",
    category_id: "mobiles-accessories",
    sub_category: "Flagship Phones",
    name: "Google Pixel 9 Pro XL 5G (Hazel Green, 256 GB, 16 GB RAM)",
    unit: "16GB RAM | 256GB ROM • Google Tensor G4 • Gemini Advanced AI",
    price: 104999,
    original_price: 114999,
    stock_quantity: 31,
    cashback_amount: 3000,
    warranty_period: "1 Year Google Warranty",
    condition: "Brand New Sealed",
    image_url: "/products/google-pixel-9-pro-xl.png",
    is_available: true,
    is_popular: true,
    rating: 4.9,
    reviews_count: 670,
    description: "Engineered by Google with Super Actua 6.8-inch display, pro triple rear camera system with 5x optical telephoto and 30x Super Res Zoom, Google Tensor G4 chip, and 7 years of Pixel OS updates.",
    variants: [
      {
        id: "px9pxl_16_128_hazel",
        ram: "16GB",
        rom: "128GB",
        storage_label: "16GB RAM + 128GB ROM",
        color: "Hazel Green",
        color_code: "#81887b",
        price: 94999,
        original_price: 104999,
        stock_quantity: 10,
        sku: "PX9PXL-16-128-HAZEL",
        image_url: "/products/google-pixel-9-pro-xl.png",
        is_active: true
      },
      {
        id: "px9pxl_16_128_obsidian",
        ram: "16GB",
        rom: "128GB",
        storage_label: "16GB RAM + 128GB ROM",
        color: "Obsidian Black",
        color_code: "#2b2d30",
        price: 94999,
        original_price: 104999,
        stock_quantity: 0,
        sku: "PX9PXL-16-128-OBSIDIAN",
        image_url: "/products/google-pixel-9-pro-xl.png",
        is_active: true
      },
      {
        id: "px9pxl_16_128_porcelain",
        ram: "16GB",
        rom: "128GB",
        storage_label: "16GB RAM + 128GB ROM",
        color: "Porcelain White",
        color_code: "#eae6df",
        price: 94999,
        original_price: 104999,
        stock_quantity: 5,
        sku: "PX9PXL-16-128-PORCELAIN",
        image_url: "/products/google-pixel-9-pro-xl.png",
        is_active: true
      },
      {
        id: "px9pxl_16_256_hazel",
        ram: "16GB",
        rom: "256GB",
        storage_label: "16GB RAM + 256GB ROM",
        color: "Hazel Green",
        color_code: "#81887b",
        price: 104999,
        original_price: 114999,
        stock_quantity: 12,
        sku: "PX9PXL-16-256-HAZEL",
        image_url: "/products/google-pixel-9-pro-xl.png",
        is_active: true
      },
      {
        id: "px9pxl_16_256_obsidian",
        ram: "16GB",
        rom: "256GB",
        storage_label: "16GB RAM + 256GB ROM",
        color: "Obsidian Black",
        color_code: "#2b2d30",
        price: 104999,
        original_price: 114999,
        stock_quantity: 4,
        sku: "PX9PXL-16-256-OBSIDIAN",
        image_url: "/products/google-pixel-9-pro-xl.png",
        is_active: true
      },
      {
        id: "px9pxl_16_256_rose",
        ram: "16GB",
        rom: "256GB",
        storage_label: "16GB RAM + 256GB ROM",
        color: "Rose Quartz",
        color_code: "#e8c5c8",
        price: 104999,
        original_price: 114999,
        stock_quantity: 0,
        sku: "PX9PXL-16-256-ROSE",
        image_url: "/products/google-pixel-9-pro-xl.png",
        is_active: true
      }
    ]
  },
  {
    id: "vivo-y400-5g",
    category: "Mobiles",
    category_id: "mobiles-accessories",
    sub_category: "5G Phones",
    name: "Vivo Y400 5G ( Olive Green, 8GB-128GB )",
    unit: "8GB RAM | 128GB ROM • 50MP Sony HD Cam • 5000mAh 44W",
    price: 31999,
    original_price: 35999,
    stock_quantity: 30,
    cashback_amount: 1000,
    image_url: "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.8,
    reviews_count: 1420,
    description: "Sleek Olive Green finish with 50MP Sony AI camera, 120Hz Ultra Vision AMOLED display, Snapdragon 4 Gen 2 5G processor, and 44W FlashCharge.",
    variants: [
      {
        id: "vy400_8_128_green",
        ram: "8GB",
        rom: "128GB",
        storage_label: "8GB RAM + 128GB ROM",
        color: "Olive Green",
        color_code: "#556b2f",
        price: 31999,
        original_price: 35999,
        stock_quantity: 16,
        sku: "VY400-8-128-GREEN",
        image_url: "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&q=80&w=600",
        is_active: true
      },
      {
        id: "vy400_8_128_black",
        ram: "8GB",
        rom: "128GB",
        storage_label: "8GB RAM + 128GB ROM",
        color: "Diamond Black",
        color_code: "#18181b",
        price: 31999,
        original_price: 35999,
        stock_quantity: 0,
        sku: "VY400-8-128-BLACK",
        image_url: "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&q=80&w=600",
        is_active: true
      },
      {
        id: "vy400_8_256_green",
        ram: "8GB",
        rom: "256GB",
        storage_label: "8GB RAM + 256GB ROM",
        color: "Olive Green",
        color_code: "#556b2f",
        price: 34999,
        original_price: 38999,
        stock_quantity: 8,
        sku: "VY400-8-256-GREEN",
        image_url: "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&q=80&w=600",
        is_active: true
      },
      {
        id: "vy400_8_256_black",
        ram: "8GB",
        rom: "256GB",
        storage_label: "8GB RAM + 256GB ROM",
        color: "Diamond Black",
        color_code: "#18181b",
        price: 34999,
        original_price: 38999,
        stock_quantity: 6,
        sku: "VY400-8-256-BLACK",
        image_url: "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&q=80&w=600",
        is_active: true
      }
    ]
  },
  {
    id: "google-pixel-9-5g",
    category: "Mobiles",
    category_id: "mobiles-accessories",
    brand: "Google Pixel",
    sub_category: "Flagship Phones",
    name: "Google Pixel 9 5G (Peony Pink, 12GB RAM, 256GB Storage) with Gemini AI",
    unit: "12GB RAM | 256GB ROM • Google Tensor G4 • 50MP Dual Camera",
    price: 79999,
    original_price: 89999,
    stock_quantity: 28,
    cashback_amount: 2500,
    warranty_period: "1 Year Official Google Warranty",
    condition: "Brand New Sealed",
    image_url: "/products/google-pixel-9.png",
    images: [
      "/products/google-pixel-9.png",
      "/products/google-pixel-9-pro-xl.png"
    ],
    is_available: true,
    is_popular: true,
    is_featured: true,
    rating: 4.8,
    reviews_count: 540,
    description: "Google Pixel 9 5G powered by the custom Google Tensor G4 processor with built-in Gemini Advanced AI assistant, 6.3-inch Actua 120Hz OLED display, and 50MP advanced camera system with Best Take and Magic Editor.",
    variants: [
      {
        id: "px9_12_256_peony",
        ram: "12GB",
        rom: "256GB",
        storage_label: "12GB RAM + 256GB ROM",
        color: "Peony Pink",
        color_code: "#e89ca4",
        price: 79999,
        original_price: 89999,
        stock_quantity: 14,
        sku: "PX9-12-256-PEONY",
        image_url: "/products/google-pixel-9.png",
        is_active: true
      },
      {
        id: "px9_12_256_obsidian",
        ram: "12GB",
        rom: "256GB",
        storage_label: "12GB RAM + 256GB ROM",
        color: "Obsidian Black",
        color_code: "#2b2d30",
        price: 79999,
        original_price: 89999,
        stock_quantity: 14,
        sku: "PX9-12-256-OBSIDIAN",
        image_url: "/products/google-pixel-9.png",
        is_active: true
      }
    ]
  },
  {
    id: "motorola-edge-50-ultra-5g",
    category: "Mobiles",
    category_id: "mobiles-accessories",
    brand: "Motorola",
    sub_category: "Flagship Phones",
    name: "Motorola Edge 50 Ultra 5G (Nordic Wood, 16GB RAM, 512GB Storage) with Pantone Validated Camera",
    unit: "16GB RAM | 512GB ROM • Snapdragon 8s Gen 3 • 125W TurboPower",
    price: 54999,
    original_price: 64999,
    stock_quantity: 22,
    cashback_amount: 1500,
    warranty_period: "1 Year Official Motorola Warranty",
    condition: "Brand New Sealed",
    image_url: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&q=80&w=600",
    images: [
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&q=80&w=600"
    ],
    is_available: true,
    is_popular: true,
    rating: 4.7,
    reviews_count: 490,
    description: "Motorola Edge 50 Ultra featuring real Nordic Wood back finish, 144Hz 1.5K pOLED curved display, 50MP triple Pantone validated camera system with 100x AI zoom, Snapdragon 8s Gen 3, and 125W TurboPower charging.",
    variants: [
      {
        id: "moto_50u_16_512_wood",
        ram: "16GB",
        rom: "512GB",
        storage_label: "16GB RAM + 512GB ROM",
        color: "Nordic Wood",
        color_code: "#a3704c",
        price: 54999,
        original_price: 64999,
        stock_quantity: 12,
        sku: "MOTO-50U-16-512-WOOD",
        image_url: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&q=80&w=600",
        is_active: true
      },
      {
        id: "moto_50u_16_512_peach",
        ram: "16GB",
        rom: "512GB",
        storage_label: "16GB RAM + 512GB ROM",
        color: "Peach Fuzz",
        color_code: "#ffbe98",
        price: 54999,
        original_price: 64999,
        stock_quantity: 10,
        sku: "MOTO-50U-16-512-PEACH",
        image_url: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&q=80&w=600",
        is_active: true
      }
    ]
  },
  {
    id: "realme-gt-7-pro-5g",
    category: "Mobiles",
    category_id: "mobiles-accessories",
    brand: "Realme",
    sub_category: "Flagship Phones",
    name: "Realme GT 7 Pro 5G (Mars Orange, 16GB RAM, 512GB Storage) | Snapdragon 8 Elite | 6500mAh Titan Battery",
    unit: "16GB RAM | 512GB ROM • Snapdragon 8 Elite • Underwater 50MP Camera",
    price: 59999,
    original_price: 69999,
    stock_quantity: 35,
    cashback_amount: 2000,
    warranty_period: "1 Year Official Realme Warranty",
    condition: "Brand New Sealed",
    image_url: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&q=80&w=600",
    images: [
      "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&q=80&w=600"
    ],
    is_available: true,
    is_popular: true,
    rating: 4.8,
    reviews_count: 720,
    description: "Realme GT 7 Pro with flagship Snapdragon 8 Elite, Eco² OLED Plus display with 6000 nits peak brightness, 6500mAh Titan battery with 120W SuperVOOC, IP69 underwater photography mode, and Sony IMX882 periscope telephoto lens.",
    variants: [
      {
        id: "realme_gt7_16_512_orange",
        ram: "16GB",
        rom: "512GB",
        storage_label: "16GB RAM + 512GB ROM",
        color: "Mars Orange",
        color_code: "#e65100",
        price: 59999,
        original_price: 69999,
        stock_quantity: 20,
        sku: "RME-GT7-16-512-ORG",
        image_url: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&q=80&w=600",
        is_active: true
      },
      {
        id: "realme_gt7_16_512_grey",
        ram: "16GB",
        rom: "512GB",
        storage_label: "16GB RAM + 512GB ROM",
        color: "Galaxy Grey",
        color_code: "#424242",
        price: 59999,
        original_price: 69999,
        stock_quantity: 15,
        sku: "RME-GT7-16-512-GRY",
        image_url: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&q=80&w=600",
        is_active: true
      }
    ]
  },
  {
    id: "redmi-note-14-pro-plus-5g",
    category: "Mobiles",
    category_id: "mobiles-accessories",
    brand: "Xiaomi / Redmi",
    sub_category: "5G Phones",
    name: "Redmi Note 14 Pro+ 5G (Spectre Blue, 12GB RAM, 512GB Storage) with 200MP OIS Camera",
    unit: "12GB RAM | 512GB ROM • Snapdragon 7s Gen 3 • 6200mAh 90W HyperCharge",
    price: 30999,
    original_price: 36999,
    stock_quantity: 40,
    cashback_amount: 1000,
    warranty_period: "1 Year Official Xiaomi Warranty",
    condition: "Brand New Sealed",
    image_url: "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&q=80&w=600",
    images: [
      "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&q=80&w=600"
    ],
    is_available: true,
    is_popular: true,
    rating: 4.8,
    reviews_count: 1560,
    description: "Redmi Note 14 Pro+ 5G equipped with ultra-clear 200MP OIS camera, 6200mAh Silicon-Carbon battery with 90W HyperCharge, IP68 waterproof rating, and 1.5K 120Hz curved AMOLED display.",
    variants: [
      {
        id: "redmi_14pp_12_512_blue",
        ram: "12GB",
        rom: "512GB",
        storage_label: "12GB RAM + 512GB ROM",
        color: "Spectre Blue",
        color_code: "#1e3a8a",
        price: 30999,
        original_price: 36999,
        stock_quantity: 25,
        sku: "REDMI-14PP-12-512-BLU",
        image_url: "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&q=80&w=600",
        is_active: true
      }
    ]
  },
  {
    id: "nothing-phone-2a-plus",
    category: "Mobiles",
    category_id: "mobiles-accessories",
    brand: "Nothing",
    sub_category: "5G Phones",
    name: "Nothing Phone (2a) Plus 5G (Metallic Grey, 12GB RAM, 256GB Storage) with Glyph Interface",
    unit: "12GB RAM | 256GB ROM • Dimensity 7350 Pro • 50MP Front & Rear",
    price: 27999,
    original_price: 33999,
    stock_quantity: 32,
    cashback_amount: 1000,
    warranty_period: "1 Year Official Nothing Warranty",
    condition: "Brand New Sealed",
    image_url: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&q=80&w=600",
    images: [
      "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&q=80&w=600"
    ],
    is_available: true,
    is_popular: true,
    rating: 4.7,
    reviews_count: 890,
    description: "Nothing Phone (2a) Plus with iconic Glyph Interface lights, custom MediaTek Dimensity 7350 Pro 5G processor, 50MP selfie camera + 50MP dual rear camera system, 5000mAh battery with 50W fast charging.",
    variants: [
      {
        id: "np_2ap_12_256_grey",
        ram: "12GB",
        rom: "256GB",
        storage_label: "12GB RAM + 256GB ROM",
        color: "Metallic Grey",
        color_code: "#4a5568",
        price: 27999,
        original_price: 33999,
        stock_quantity: 18,
        sku: "NP-2AP-12-256-GRY",
        image_url: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&q=80&w=600",
        is_active: true
      },
      {
        id: "np_2ap_12_256_black",
        ram: "12GB",
        rom: "256GB",
        storage_label: "12GB RAM + 256GB ROM",
        color: "Black",
        color_code: "#18181b",
        price: 27999,
        original_price: 33999,
        stock_quantity: 14,
        sku: "NP-2AP-12-256-BLK",
        image_url: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&q=80&w=600",
        is_active: true
      }
    ]
  },
  {
    id: "iqoo-13-5g-legend",
    category: "Mobiles",
    category_id: "mobiles-accessories",
    brand: "iQOO",
    sub_category: "Flagship Phones",
    name: "iQOO 13 5G (Legend White BMW M Motorsport Edition, 16GB RAM, 512GB Storage) | Snapdragon 8 Elite",
    unit: "16GB RAM | 512GB ROM • Snapdragon 8 Elite • 2K 144Hz Q10 Display • 120W FlashCharge",
    price: 54999,
    original_price: 62999,
    stock_quantity: 26,
    cashback_amount: 2000,
    warranty_period: "1 Year Official iQOO Warranty",
    condition: "Brand New Sealed",
    image_url: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&q=80&w=600",
    images: [
      "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&q=80&w=600"
    ],
    is_available: true,
    is_popular: true,
    rating: 4.9,
    reviews_count: 610,
    description: "iQOO 13 5G flagship performance powerhouse featuring Qualcomm Snapdragon 8 Elite, Supercomputing chip Q2, 2K 144Hz BOE Q10 LTPO display, Halo LED breathing light, and 6150mAh BlueVolt battery with 120W ultra-fast FlashCharge.",
    variants: [
      {
        id: "iqoo13_16_512_legend",
        ram: "16GB",
        rom: "512GB",
        storage_label: "16GB RAM + 512GB ROM",
        color: "Legend White (BMW M)",
        color_code: "#f8fafc",
        price: 54999,
        original_price: 62999,
        stock_quantity: 16,
        sku: "IQOO13-16-512-LEG",
        image_url: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&q=80&w=600",
        is_active: true
      },
      {
        id: "iqoo13_16_512_nardo",
        ram: "16GB",
        rom: "512GB",
        storage_label: "16GB RAM + 512GB ROM",
        color: "Nardo Grey",
        color_code: "#4b5563",
        price: 54999,
        original_price: 62999,
        stock_quantity: 10,
        sku: "IQOO13-16-512-GRY",
        image_url: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&q=80&w=600",
        is_active: true
      }
    ]
  },

  // ==================== 2. OLD / REFURBISHED MOBILES ====================
  {
    id: "refurbished-iphone-14-pro",
    category: "Old / Refurbished Mobiles",
    category_id: "old-refurbished-mobiles",
    sub_category: "Refurbished iPhones",
    name: "Apple iPhone 14 Pro (Refurbished - Superb Grade A+)",
    unit: "128GB Deep Purple • 94% Battery Health • 6M Warranty",
    price: 64999,
    original_price: 129900,
    stock_quantity: 12,
    cashback_amount: 1500,
    condition: "Superb (Grade A+)",
    battery_health: "94% Battery Health",
    warranty_period: "6 Months Seller Replacement Warranty",
    image_url: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.9,
    reviews_count: 820,
    description: "Certified Refurbished iPhone 14 Pro with 32-point technical quality check. Flawless Grade A+ cosmetic condition with zero visible scratches, genuine 94% battery health, Dynamic Island, 48MP Pro Camera, and 6-Month comprehensive replacement warranty with charging cable."
  },
  {
    id: "refurbished-iphone-13-midnight",
    category: "Old / Refurbished Mobiles",
    category_id: "old-refurbished-mobiles",
    sub_category: "Refurbished iPhones",
    name: "Apple iPhone 13 (Refurbished - Like New)",
    unit: "128GB Midnight • 92% Battery Health • Fully Tested",
    price: 36999,
    original_price: 59900,
    stock_quantity: 18,
    cashback_amount: 1000,
    condition: "Like New (Grade A)",
    battery_health: "92% Battery Health",
    warranty_period: "6 Months Warranty",
    image_url: "https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.8,
    reviews_count: 1450,
    description: "Pre-owned Apple iPhone 13 128GB in Like-New condition. Tested and certified by tech experts with 92% battery health, original OLED display, functional FaceID & TrueTone, backed by a 6-month warranty."
  },
  {
    id: "refurbished-s23-ultra",
    category: "Old / Refurbished Mobiles",
    category_id: "old-refurbished-mobiles",
    sub_category: "Refurbished Android",
    name: "Samsung Galaxy S23 Ultra 5G (Refurbished - Superb)",
    unit: "12GB RAM | 256GB ROM • Phantom Black • 96% Battery",
    price: 58999,
    original_price: 124999,
    stock_quantity: 8,
    cashback_amount: 2000,
    condition: "Superb (Grade A+)",
    battery_health: "96% Battery Health",
    warranty_period: "6 Months Full Warranty",
    image_url: "/products/samsung-galaxy-s25-ultra.png",
    is_available: true,
    is_popular: true,
    rating: 4.9,
    reviews_count: 610,
    description: "Certified Second-Hand Samsung Galaxy S23 Ultra 5G with S-Pen. 200MP Quad Camera with 100x zoom, Snapdragon 8 Gen 2, pristine screen with anti-reflective finish, 96% battery health, fully disinfected and tested."
  },
  {
    id: "refurbished-oneplus-11",
    category: "Old / Refurbished Mobiles",
    category_id: "old-refurbished-mobiles",
    sub_category: "Refurbished Android",
    name: "OnePlus 11 5G (Refurbished - Grade A+)",
    unit: "16GB RAM | 256GB ROM • Titan Black • 100W Fast Charge",
    price: 32999,
    original_price: 61999,
    stock_quantity: 10,
    cashback_amount: 800,
    condition: "Grade A+ (Superb)",
    battery_health: "95% Battery Health",
    warranty_period: "6 Months Warranty",
    image_url: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: false,
    rating: 4.7,
    reviews_count: 430,
    description: "Pre-owned OnePlus 11 5G with 16GB RAM and Hasselblad camera system. Tested across 45 hardware checkpoints, certified with 95% battery capacity and 100W SuperVOOC charging support."
  },

  // ==================== 3. MOBILE ACCESSORIES ====================
  {
    id: "apple-20w-charger",
    category: "Mobile Accessories",
    category_id: "mobile-accessories",
    sub_category: "Chargers & Adapters",
    name: "Apple 20W USB-C Fast Power Adapter & Type-C Cable Combo",
    unit: "20W PD Fast Charging • Official Apple Genuine Accessory",
    price: 1899,
    original_price: 2199,
    stock_quantity: 50,
    cashback_amount: 100,
    image_url: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.8,
    reviews_count: 3200,
    description: "Official Apple 20W USB-C Power Adapter provides fast, efficient charging at home, in the office, or on the go. 50% charge in just 30 minutes for iPhone 16 & 15 series."
  },
  {
    id: "magsafe-wireless-powerbank-10000mah",
    category: "Mobile Accessories",
    category_id: "mobile-accessories",
    sub_category: "Power Banks",
    name: "MagSafe 10,000mAh Magnetic Wireless Fast Power Bank (22.5W PD)",
    unit: "10000mAh • 22.5W Fast Charge • Strong Magnet Hold • Type-C In/Out",
    price: 2499,
    original_price: 4999,
    stock_quantity: 40,
    cashback_amount: 150,
    image_url: "https://images.unsplash.com/photo-1609592424357-6c243859600e?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.8,
    reviews_count: 1120,
    description: "Ultra-slim magnetic powerbank with strong N52 neodymium magnets for snap-on charging on iPhone 12/13/14/15/16 and Qi-enabled Android phones. Includes LED battery percentage display."
  },
  {
    id: "spigen-ultra-hybrid-case-iphone",
    category: "Mobile Accessories",
    category_id: "mobile-accessories",
    sub_category: "Cases & Covers",
    name: "Spigen Ultra Hybrid Military-Grade Crystal Clear Drop-Proof Case",
    unit: "Air Cushion Tech • Anti-Yellowing Clear • Raised Camera Bezel",
    price: 1299,
    original_price: 2499,
    stock_quantity: 60,
    cashback_amount: 50,
    image_url: "https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: false,
    rating: 4.9,
    reviews_count: 2400,
    description: "Certified military-grade drop protection case with crystal clear anti-yellowing backplate and reinforced shock-absorbing bumper edges."
  },
  {
    id: "fast-pd-65w-gan-charger",
    category: "Mobile Accessories",
    category_id: "mobile-accessories",
    sub_category: "Chargers & Adapters",
    name: "65W GaN Triple Port (2x Type-C + 1x USB-A) Fast Multi-Device Charger",
    unit: "65W GaN III Tech • Laptop & Mobile SuperFast Charging",
    price: 2199,
    original_price: 3999,
    stock_quantity: 35,
    cashback_amount: 100,
    image_url: "https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.8,
    reviews_count: 980,
    description: "Gallium Nitride (GaN III) compact wall adapter capable of charging MacBook, iPhone, and Galaxy devices simultaneously at peak wattage without overheating."
  },
  {
    id: "9d-tempered-glass-screen-guard",
    category: "Mobile Accessories",
    category_id: "mobile-accessories",
    sub_category: "Tempered Glass",
    name: "9D Edge-to-Edge Curved Tempered Glass Screen Protector (Pack of 2)",
    unit: "9H Hardness • Oleophobic Anti-Fingerprint • HD Clarity",
    price: 399,
    original_price: 999,
    stock_quantity: 100,
    cashback_amount: 20,
    image_url: "https://images.unsplash.com/photo-1601784551446-20c9e07cdbdb?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.7,
    reviews_count: 4200,
    description: "Ultra-tough 9H tempered glass with Japanese Asahi glass core, bubble-free adhesive, anti-scratch surface, and smooth 2.5D rounded edges."
  },
  {
    id: "sandisk-128gb-extreme-microsd",
    category: "Mobile Accessories",
    category_id: "mobile-accessories",
    sub_category: "Storage",
    name: "SanDisk Extreme 128GB UHS-I U3 A2 High-Speed MicroSDXC Card with SD Adapter",
    unit: "Up to 190MB/s Read • 4K UHD Video Recording • 10-Year Warranty",
    price: 1199,
    original_price: 2499,
    stock_quantity: 45,
    cashback_amount: 50,
    image_url: "https://images.unsplash.com/photo-1628155930542-3c7a64e2c833?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.9,
    reviews_count: 3100,
    description: "High performance memory card ideal for smartphones, action cameras, and drones with up to 190MB/s transfer speeds and A2 rating for faster app performance."
  },
  {
    id: "anker-usb-c-braided-cable",
    category: "Mobile Accessories",
    category_id: "mobile-accessories",
    sub_category: "Cables",
    name: "Anker PowerLine III Flow USB-C to USB-C 100W Fast Charging Cable (6ft / 1.8m)",
    unit: "100W Power Delivery • Silicone Soft-Touch • 25,000 Bend Lifespan",
    price: 899,
    original_price: 1599,
    stock_quantity: 80,
    cashback_amount: 50,
    image_url: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: false,
    rating: 4.8,
    reviews_count: 1850,
    description: "Super-strong braided Type-C to Type-C cable supporting 100W PD fast charging for all laptops, tablets, and smartphones."
  },
  {
    id: "magnetic-wireless-car-mount",
    category: "Mobile Accessories",
    category_id: "mobile-accessories",
    sub_category: "Chargers & Adapters",
    name: "15W Fast Qi Magnetic Wireless Car Charger & Air Vent Mount Holder",
    unit: "15W Fast Wireless • 360° Rotation • Auto Clamping & Strong Magnet",
    price: 1699,
    original_price: 3299,
    stock_quantity: 30,
    cashback_amount: 100,
    image_url: "https://images.unsplash.com/photo-1585338107529-13afc5f02586?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.7,
    reviews_count: 760,
    description: "Hands-free magnetic wireless dashboard/air-vent car charger with smart overheating protection and ultra-firm grip over bumpy roads."
  },

  // ==================== 4. JEWELLERY ====================
  {
    id: "royal-gold-necklace-set",
    category: "Jewellery",
    category_id: "jewellery",
    sub_category: "Necklace Sets & Chokers",
    name: "22K Gold Plated Royal Kundan & Pearl Choker Necklace Set with Jhumkas",
    unit: "22K Gold Polish • Handcrafted Kundan • Matching Jhumka Earrings",
    price: 4999,
    original_price: 12999,
    stock_quantity: 15,
    cashback_amount: 300,
    warranty_period: "1 Year Polish & Plating Guarantee",
    image_url: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.9,
    reviews_count: 850,
    description: "Exquisite bridal Kundan choker necklace handcrafted with high-grade semi-precious stones, natural freshwater pearls, and durable 22K micron gold plating. Comes with velvet luxury gift box."
  },
  {
    id: "solitaire-diamond-ring",
    category: "Jewellery",
    category_id: "jewellery",
    sub_category: "Silver & Moissanite",
    name: "925 Sterling Silver 2.0 Carat Solitaire Moissanite Diamond Ring (VVS1)",
    unit: "Pure 925 Silver • 2ct GRA Certified Moissanite • Anti-Tarnish",
    price: 3499,
    original_price: 7999,
    stock_quantity: 20,
    cashback_amount: 250,
    warranty_period: "Lifetime Authenticity Certificate Included",
    image_url: "https://images.unsplash.com/photo-1605100804763-247f67b3557e?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.9,
    reviews_count: 640,
    description: "Brilliant 2.0 carat round cut GRA certified Moissanite diamond set in pure 925 sterling silver with rhodium polish. Passes diamond tester, superior fire & brilliance."
  },

  // ==================== 4.5. FASHION & APPAREL ====================
  {
    id: "levis-511-slim-fit-jeans",
    category: "Fashion",
    category_id: "fashion",
    brand: "Levi's",
    sub_category: "Jeans & Trousers",
    name: "Levi's 511 Slim Fit Stretch Dark Indigo Denim Jeans",
    unit: "99% Cotton 1% Elastane • All-Day Comfort Stretch • Signature Arcuate Stitch",
    price: 2699,
    original_price: 4999,
    stock_quantity: 45,
    cashback_amount: 150,
    warranty_period: "100% Original Brand Guarantee",
    image_url: "https://images.unsplash.com/photo-1542272604-780c96856592?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.8,
    reviews_count: 1420,
    description: "Classic Levi's 511 modern slim-fit jeans with room to move. Built with premium ring-spun denim, copper rivets, zip fly, and authentic 5-pocket styling.",
    variants: [
      { id: "lev-30-ind", ram: "30", rom: "Regular", storage_label: "Size 30W", color: "Dark Indigo", color_code: "#1b263b", price: 2699, original_price: 4999, stock_quantity: 15, sku: "LEV-511-30-IND" },
      { id: "lev-32-ind", ram: "32", rom: "Regular", storage_label: "Size 32W", color: "Dark Indigo", color_code: "#1b263b", price: 2699, original_price: 4999, stock_quantity: 18, sku: "LEV-511-32-IND" },
      { id: "lev-34-ind", ram: "34", rom: "Regular", storage_label: "Size 34W", color: "Dark Indigo", color_code: "#1b263b", price: 2699, original_price: 4999, stock_quantity: 12, sku: "LEV-511-34-IND" },
    ]
  },
  {
    id: "tommy-hilfiger-egyptian-cotton-shirt",
    category: "Fashion",
    category_id: "fashion",
    brand: "Tommy Hilfiger",
    sub_category: "Men's Shirts & Polos",
    name: "Tommy Hilfiger Tailored Fit Pure Giza Egyptian Cotton Formal Shirt",
    unit: "100% Premium Egyptian Giza Cotton • Wrinkle Resistant • Semi-Spread Collar",
    price: 3499,
    original_price: 6999,
    stock_quantity: 40,
    cashback_amount: 200,
    image_url: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.9,
    reviews_count: 980,
    description: "Tailored luxury formal shirt woven from long-staple Egyptian Giza cotton with mother-of-pearl buttons, embroidered Tommy flag on chest, and double-button barrel cuffs.",
    variants: [
      { id: "th-39-wht", ram: "39 (M)", rom: "Slim Fit", storage_label: "Size 39 (M)", color: "Crisp White", color_code: "#FFFFFF", price: 3499, original_price: 6999, stock_quantity: 14, sku: "TH-EGY-39-WHT" },
      { id: "th-40-wht", ram: "40 (L)", rom: "Slim Fit", storage_label: "Size 40 (L)", color: "Crisp White", color_code: "#FFFFFF", price: 3499, original_price: 6999, stock_quantity: 16, sku: "TH-EGY-40-WHT" },
      { id: "th-42-blu", ram: "42 (XL)", rom: "Slim Fit", storage_label: "Size 42 (XL)", color: "Sky Blue", color_code: "#87CEEB", price: 3499, original_price: 6999, stock_quantity: 10, sku: "TH-EGY-42-BLU" },
    ]
  },
  {
    id: "nike-drifit-sportswear-tee",
    category: "Fashion",
    category_id: "fashion",
    brand: "Nike",
    sub_category: "T-Shirts & Sportswear",
    name: "Nike Dri-FIT Legend Athletic Training & Gym Performance T-Shirt",
    unit: "Moisture-Wicking Dri-FIT Fabric • Anti-Odor • Athletic Fit",
    price: 1499,
    original_price: 2495,
    stock_quantity: 60,
    cashback_amount: 100,
    image_url: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.8,
    reviews_count: 2100,
    description: "Engineered with ultra-soft, breathable Dri-FIT technology that pulls sweat away from skin for quicker evaporation, keeping you dry and focused.",
    variants: [
      { id: "nike-m-blk", ram: "M", rom: "Athletic", storage_label: "Size Medium (M)", color: "Black & White Swoosh", color_code: "#000000", price: 1499, original_price: 2495, stock_quantity: 20, sku: "NIKE-DF-M-BLK" },
      { id: "nike-l-blk", ram: "L", rom: "Athletic", storage_label: "Size Large (L)", color: "Black & White Swoosh", color_code: "#000000", price: 1499, original_price: 2495, stock_quantity: 25, sku: "NIKE-DF-L-BLK" },
      { id: "nike-xl-red", ram: "XL", rom: "Athletic", storage_label: "Size XL", color: "University Red", color_code: "#CC0000", price: 1499, original_price: 2495, stock_quantity: 15, sku: "NIKE-DF-XL-RED" },
    ]
  },
  {
    id: "zara-floral-wrap-maxi-dress",
    category: "Fashion",
    category_id: "fashion",
    brand: "Zara",
    sub_category: "Women's Dresses & Kurtis",
    name: "Zara Flowy Floral Print Summer Wrap Maxi Dress with Tie Belt",
    unit: "100% Breathable Georgette Viscose • V-Neckline • Flared Hem",
    price: 2999,
    original_price: 5590,
    stock_quantity: 35,
    cashback_amount: 200,
    image_url: "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.9,
    reviews_count: 730,
    description: "Chic floral printed wrap maxi dress from Zara featuring a surplice neckline, short flutter sleeves, detachable fabric tie belt, and a dramatic ruffled tiered hemline.",
    variants: [
      { id: "zara-s-flr", ram: "S", rom: "Maxi", storage_label: "Size Small (S)", color: "Emerald Floral", color_code: "#046307", price: 2999, original_price: 5590, stock_quantity: 12, sku: "ZARA-DRS-S-FLR" },
      { id: "zara-m-flr", ram: "M", rom: "Maxi", storage_label: "Size Medium (M)", color: "Emerald Floral", color_code: "#046307", price: 2999, original_price: 5590, stock_quantity: 15, sku: "ZARA-DRS-M-FLR" },
      { id: "zara-l-flr", ram: "L", rom: "Maxi", storage_label: "Size Large (L)", color: "Emerald Floral", color_code: "#046307", price: 2999, original_price: 5590, stock_quantity: 8, sku: "ZARA-DRS-L-FLR" },
    ]
  },
  {
    id: "us-polo-classic-pique-polo",
    category: "Fashion",
    category_id: "fashion",
    brand: "US Polo Assn",
    sub_category: "Men's Shirts & Polos",
    name: "U.S. Polo Assn. Signature Embroidered Pique Cotton Regular Polo Shirt",
    unit: "100% Combed Pique Cotton • Ribbed Collar • Double Horsemen Logo",
    price: 1699,
    original_price: 2999,
    stock_quantity: 50,
    cashback_amount: 120,
    image_url: "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.7,
    reviews_count: 1150,
    description: "Classic American heritage polo tailored from heavyweight breathable pique cotton with contrast tipping on ribbed polo collar and sleeves.",
    variants: [
      { id: "usp-m-nvy", ram: "M", rom: "Regular", storage_label: "Size M (38)", color: "Navy Blue", color_code: "#000080", price: 1699, original_price: 2999, stock_quantity: 20, sku: "USP-POLO-M-NVY" },
      { id: "usp-l-nvy", ram: "L", rom: "Regular", storage_label: "Size L (40)", color: "Navy Blue", color_code: "#000080", price: 1699, original_price: 2999, stock_quantity: 18, sku: "USP-POLO-L-NVY" },
      { id: "usp-xl-wht", ram: "XL", rom: "Regular", storage_label: "Size XL (42)", color: "Bright White", color_code: "#FFFFFF", price: 1699, original_price: 2999, stock_quantity: 12, sku: "USP-POLO-XL-WHT" },
    ]
  },
  {
    id: "manyavar-royal-jacquard-kurta-set",
    category: "Fashion",
    category_id: "fashion",
    brand: "Manyavar",
    sub_category: "Ethnic & Kurta Sets",
    name: "Manyavar Royal Jacquard Art Silk Embroidered Kurta & Churidar Set",
    unit: "Art Silk Jacquard • Mandarin Collar • Gold Buttons • Churidar Included",
    price: 3999,
    original_price: 7999,
    stock_quantity: 30,
    cashback_amount: 300,
    image_url: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.9,
    reviews_count: 880,
    description: "Regal festive wear kurta set from Manyavar crafted from richly textured jacquard art silk with delicate zari thread embroidery on the collar and placket. Includes matching churidar bottoms.",
    variants: [
      { id: "man-38-mrn", ram: "38 (M)", rom: "Traditional", storage_label: "Size 38 (M)", color: "Maroon & Gold", color_code: "#800000", price: 3999, original_price: 7999, stock_quantity: 10, sku: "MAN-KTA-38-MRN" },
      { id: "man-40-mrn", ram: "40 (L)", rom: "Traditional", storage_label: "Size 40 (L)", color: "Maroon & Gold", color_code: "#800000", price: 3999, original_price: 7999, stock_quantity: 12, sku: "MAN-KTA-40-MRN" },
      { id: "man-42-gld", ram: "42 (XL)", rom: "Traditional", storage_label: "Size 42 (XL)", color: "Royal Gold", color_code: "#FFD700", price: 3999, original_price: 7999, stock_quantity: 8, sku: "MAN-KTA-42-GLD" },
    ]
  },
  {
    id: "biba-anarkali-suit-set",
    category: "Fashion",
    category_id: "fashion",
    brand: "Biba",
    sub_category: "Women's Dresses & Kurtis",
    name: "Biba Printed Cotton Anarkali Kurta Set with Silk Blend Dupatta & Palazzos",
    unit: "Pure Cotton • 3-Piece Set (Kurta, Palazzo, Dupatta) • Gotapatti Work",
    price: 3299,
    original_price: 6599,
    stock_quantity: 28,
    cashback_amount: 250,
    image_url: "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.9,
    reviews_count: 650,
    description: "Stunning 3-piece ethnic Anarkali suit set from Biba with authentic Jaipur handblock prints, shimmering gotapatti lace detailing, and a lightweight printed Chanderi silk dupatta.",
    variants: [
      { id: "biba-32-blu", ram: "32 (S)", rom: "Anarkali", storage_label: "Size 32 (S)", color: "Royal Indigo Blue", color_code: "#1a237e", price: 3299, original_price: 6599, stock_quantity: 8, sku: "BIBA-ANK-32-BLU" },
      { id: "biba-34-blu", ram: "34 (M)", rom: "Anarkali", storage_label: "Size 34 (M)", color: "Royal Indigo Blue", color_code: "#1a237e", price: 3299, original_price: 6599, stock_quantity: 12, sku: "BIBA-ANK-34-BLU" },
      { id: "biba-36-pnk", ram: "36 (L)", rom: "Anarkali", storage_label: "Size 36 (L)", color: "Rani Pink", color_code: "#e91e63", price: 3299, original_price: 6599, stock_quantity: 8, sku: "BIBA-ANK-36-PNK" },
    ]
  },
  {
    id: "raymond-formal-slim-trousers",
    category: "Fashion",
    category_id: "fashion",
    brand: "Raymond",
    sub_category: "Jeans & Trousers",
    name: "Raymond Fine Wool-Blend Slim Fit Wrinkle-Free Formal Trousers",
    unit: "Fine Poly-Wool Blend • Flat Front • Cross Pockets • Non-Iron Finish",
    price: 2199,
    original_price: 4299,
    stock_quantity: 40,
    cashback_amount: 150,
    image_url: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.8,
    reviews_count: 920,
    description: "Executive tailored formal trousers from Raymond designed with breathable luxury poly-wool fabric that resists creases throughout long business hours and conferences.",
    variants: [
      { id: "ray-32-chr", ram: "32W", rom: "Flat Front", storage_label: "Size 32W", color: "Charcoal Grey", color_code: "#36454f", price: 2199, original_price: 4299, stock_quantity: 15, sku: "RAY-TRS-32-CHR" },
      { id: "ray-34-chr", ram: "34W", rom: "Flat Front", storage_label: "Size 34W", color: "Charcoal Grey", color_code: "#36454f", price: 2199, original_price: 4299, stock_quantity: 15, sku: "RAY-TRS-34-CHR" },
      { id: "ray-36-blk", ram: "36W", rom: "Flat Front", storage_label: "Size 36W", color: "Midnight Black", color_code: "#000000", price: 2199, original_price: 4299, stock_quantity: 10, sku: "RAY-TRS-36-BLK" },
    ]
  },
  {
    id: "puma-ferrari-motorsport-jacket",
    category: "Fashion",
    category_id: "fashion",
    brand: "Puma",
    sub_category: "Jackets & Outerwear",
    name: "Puma Scuderia Ferrari Motorsport Full-Zip Track Bomber Jacket",
    unit: "Scuderia Ferrari Shield Badge • Wind-Resistant Shell • Ergonomic Cutlines",
    price: 4499,
    original_price: 8999,
    stock_quantity: 25,
    cashback_amount: 300,
    image_url: "https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.9,
    reviews_count: 710,
    description: "Official Puma x Scuderia Ferrari collection jacket featuring premium double-knit fabric, articulated sleeves for unrestricted movement, and iconic Ferrari TPU shield emblem.",
    variants: [
      { id: "puma-m-red", ram: "M", rom: "Track Fit", storage_label: "Size Medium (M)", color: "Rosso Corsa Red", color_code: "#D40000", price: 4499, original_price: 8999, stock_quantity: 10, sku: "PUMA-SF-M-RED" },
      { id: "puma-l-red", ram: "L", rom: "Track Fit", storage_label: "Size Large (L)", color: "Rosso Corsa Red", color_code: "#D40000", price: 4499, original_price: 8999, stock_quantity: 10, sku: "PUMA-SF-L-RED" },
      { id: "puma-xl-blk", ram: "XL", rom: "Track Fit", storage_label: "Size XL", color: "Puma Black", color_code: "#0B0B0C", price: 4499, original_price: 8999, stock_quantity: 5, sku: "PUMA-SF-XL-BLK" },
    ]
  },
  {
    id: "calvin-klein-monogram-tee",
    category: "Fashion",
    category_id: "fashion",
    brand: "Calvin Klein",
    sub_category: "T-Shirts & Sportswear",
    name: "Calvin Klein Jeans Organic Cotton Monogram Logo Crewneck T-Shirt",
    unit: "100% Organic Soft Cotton • Signature CK Chest Monogram • Ribbed Crewneck",
    price: 1999,
    original_price: 3999,
    stock_quantity: 45,
    cashback_amount: 150,
    image_url: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.8,
    reviews_count: 890,
    description: "Iconic Calvin Klein Jeans minimalist t-shirt cut from pure sustainable organic jersey cotton with archival boxed monogram graphic screen-print on front chest.",
    variants: [
      { id: "ck-s-blk", ram: "S", rom: "Regular", storage_label: "Size Small (S)", color: "Black", color_code: "#000000", price: 1999, original_price: 3999, stock_quantity: 15, sku: "CK-TEE-S-BLK" },
      { id: "ck-m-blk", ram: "M", rom: "Regular", storage_label: "Size Medium (M)", color: "Black", color_code: "#000000", price: 1999, original_price: 3999, stock_quantity: 18, sku: "CK-TEE-M-BLK" },
      { id: "ck-l-wht", ram: "L", rom: "Regular", storage_label: "Size Large (L)", color: "Optical White", color_code: "#FFFFFF", price: 1999, original_price: 3999, stock_quantity: 12, sku: "CK-TEE-L-WHT" },
    ]
  },
  {
    id: "luxury-chronograph-watch",
    category: "Fashion",
    category_id: "fashion",
    brand: "Tommy Hilfiger",
    sub_category: "Watches & Chronographs",
    name: "Men's Luxury Sapphire Glass Waterproof Quartz Chronograph Watch",
    unit: "Solid Stainless Steel • Sapphire Crystal Glass • 5ATM Water Resistant",
    price: 2999,
    original_price: 8499,
    stock_quantity: 25,
    cashback_amount: 200,
    warranty_period: "2 Years Movement Warranty",
    image_url: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: false,
    rating: 4.8,
    reviews_count: 530,
    description: "Precision Japanese quartz movement with functional 3-dial chronograph, luminous watch hands, scratch-resistant sapphire crystal glass, and solid stainless steel butterfly clasp."
  },
  {
    id: "designer-leather-handbag",
    category: "Fashion",
    category_id: "fashion",
    brand: "Zara",
    sub_category: "Handbags & Purses",
    name: "Italian Structured Vegan Leather Shoulder Handbag & Crossbody Bag",
    unit: "Premium Vegan Leather • Gold Hardware • Multi-Compartment",
    price: 2499,
    original_price: 5999,
    stock_quantity: 30,
    cashback_amount: 150,
    image_url: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.7,
    reviews_count: 420,
    description: "Elegant structured designer handbag crafted from scratch-resistant Italian PU leather with polished gold-tone hardware, detachable shoulder strap, and spacious zippered dividers."
  },

  // ==================== 5. EV VEHICLES ====================
  {
    id: "ola-s1-pro-gen-2",
    category: "EV Vehicles",
    category_id: "ev-vehicles",
    sub_category: "Electric Scooters",
    name: "Ola S1 Pro Gen 2 Electric Scooter (Midnight Blue, 4 kWh Battery)",
    unit: "195 km Certified Range • 120 km/h Top Speed • Hypercharge • Touch Display",
    price: 129999,
    original_price: 147499,
    stock_quantity: 6,
    cashback_amount: 5000,
    warranty_period: "8 Years / 80,000 km Battery Warranty",
    image_url: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.9,
    reviews_count: 320,
    description: "Next-gen high performance electric scooter with 11 kW peak motor power, 0-40 km/h in just 2.6 seconds, 195 km range, 7-inch touchscreen dash with MoveOS 4 navigation, cruise control, proximity unlock, and 34L underseat storage."
  },
  {
    id: "ather-450x-gen-3",
    category: "EV Vehicles",
    category_id: "ev-vehicles",
    sub_category: "Electric Scooters",
    name: "Ather 450X Gen 3 Pro Electric Scooter (Space Grey, 3.7 kWh)",
    unit: "150 km TrueRange • Warp Mode • Google Maps Touchscreen Dash",
    price: 139999,
    original_price: 155000,
    stock_quantity: 5,
    cashback_amount: 5000,
    warranty_period: "5 Years Battery & Motor Warranty",
    image_url: "https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.9,
    reviews_count: 410,
    description: "Premium smart electric scooter featuring Ather Warp Mode, IP67 waterproof lithium-ion battery pack, live Google Maps onboard navigation, AutoHold hill assist, and aluminium chassis."
  },
  {
    id: "tvs-iqube-st",
    category: "EV Vehicles",
    category_id: "ev-vehicles",
    sub_category: "Electric Scooters",
    name: "TVS iQube ST Electric Scooter (Pearl White, 3.4 kWh)",
    unit: "145 km Real Range • 7\" TFT Touchscreen • 32L Storage • Alexa Skill",
    price: 124999,
    original_price: 138000,
    stock_quantity: 8,
    cashback_amount: 4000,
    warranty_period: "5 Years / 70,000 km Warranty",
    image_url: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: false,
    rating: 4.8,
    reviews_count: 280,
    description: "Reliable family electric scooter with silent BLDC hub motor, 7-inch full color TFT touchscreen, Alexa voice assistance integration, fast charging, and plush dual suspension."
  },
  {
    id: "revolt-rv400-ev-bike",
    category: "EV Vehicles",
    category_id: "ev-vehicles",
    sub_category: "Electric Bikes",
    name: "Revolt RV400 AI-Enabled Electric Motorcycle (Cosmic Black)",
    unit: "150 km Eco Range • 85 km/h • Removable Battery • Sound Simulator",
    price: 134999,
    original_price: 149999,
    stock_quantity: 4,
    cashback_amount: 5000,
    warranty_period: "5 Years / 75,000 km Battery Warranty",
    image_url: "https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.8,
    reviews_count: 195,
    description: "India's first AI electric motorcycle. 3.24 kWh portable swappable lithium-ion battery (charge anywhere at home), customizable synthetic exhaust sound simulator, USD front forks, and smartphone app telemetry."
  },

  // ==================== 6. COMPUTER & TABLETS ====================
  {
    id: "ipad-pro-13-m4",
    category: "Computers & Tablets",
    category_id: "computers-tablets",
    sub_category: "iPads & Tablets",
    name: "Apple iPad Pro 13-inch M4 Ultra Retina XDR (Space Black)",
    unit: "256 GB, 512 GB, 1 TB Nano-Texture, 2 TB Cellular",
    price: 129900,
    original_price: 139900,
    stock_quantity: 25,
    cashback_amount: 3000,
    image_url: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&q=80&w=600",
    images: [
      "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&q=80&w=600",
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&q=80&w=600"
    ],
    is_available: true,
    is_popular: true,
    rating: 4.9,
    reviews_count: 840,
    description: "The thinnest Apple product ever with breakthrough Ultra Retina XDR tandem OLED display. Powered by the next-generation Apple M4 chip with hardware-accelerated ray tracing, 4K ProRes video support, and full Apple Pencil Pro support with haptic feedback."
  },
  {
    id: "macbook-air-m3",
    category: "Computers & Tablets",
    category_id: "computers-tablets",
    sub_category: "Laptops",
    name: "Apple MacBook Air 15-inch M3 Chip (Midnight, 16 GB RAM, 512 GB SSD)",
    unit: "16GB Unified Memory | 512GB SSD • 15.3\" Liquid Retina • 18h Battery",
    price: 134990,
    original_price: 144900,
    stock_quantity: 25,
    cashback_amount: 3500,
    image_url: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.9,
    reviews_count: 580,
    description: "Strikingly thin 15-inch design powered by Apple M3 8-core CPU and 10-core GPU. Liquid Retina display with 500 nits brightness, MagSafe 3 charging, and 1080p FaceTime HD camera."
  },
  {
    id: "asus-tuf-gaming-f15",
    category: "Computers & Tablets",
    category_id: "computers-tablets",
    sub_category: "Gaming Laptops",
    name: "ASUS TUF Gaming F15 (16 GB RAM, 512 GB SSD, RTX 4060, Intel i7-13th Gen)",
    unit: "16GB DDR5 | 512GB Gen4 SSD • RTX 4060 8GB • 144Hz FHD",
    price: 84990,
    original_price: 104990,
    stock_quantity: 25,
    cashback_amount: 2500,
    image_url: "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.8,
    reviews_count: 940,
    description: "Geared for serious gaming and real-world durability. Intel Core i7-13620H processor, NVIDIA GeForce RTX 4060 Laptop GPU with MUX Switch, 144Hz adaptive-sync display, and military-grade toughness."
  },

  // ==================== 7. TV & AUDIO ====================
  {
    id: "samsung-65-qled-4k",
    category: "TV & Audio",
    category_id: "tv-audio",
    sub_category: "4K Smart TVs",
    name: "Samsung 65-inch Crystal 4K Vivid Pro Ultra HD Smart TV",
    unit: "65\" 4K UHD (3840x2160) • PurColor • Object Tracking Sound Lite",
    price: 62990,
    original_price: 89900,
    stock_quantity: 25,
    cashback_amount: 2000,
    image_url: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.8,
    reviews_count: 1150,
    description: "Crystal Processor 4K upscale engine, 4K Upscaling, HDR10+, Motion Xcelerator, SolarCell Remote, Q-Symphony sound sync, and smart IoT Hub built-in."
  },
  {
    id: "sony-wh-1000xm5",
    category: "TV & Audio",
    category_id: "tv-audio",
    sub_category: "Noise Canceling Headphones",
    name: "Sony WH-1000XM5 Wireless Industry Leading Noise Canceling Headphones",
    unit: "Auto NC Optimizer • 30h Battery with Quick Charge • Hi-Res LDAC",
    price: 26990,
    original_price: 34990,
    stock_quantity: 25,
    cashback_amount: 1000,
    image_url: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.9,
    reviews_count: 3200,
    description: "Two processors and 8 microphones for unparalleled noise cancellation. Ultra-comfortable lightweight design with soft fit leather, Speak-to-Chat, and 30 hours of playback."
  },

  // ==================== 8. KITCHEN APPLIANCES ====================
  {
    id: "elgi-ultra-wet-grinder",
    category: "Kitchen Appliances",
    category_id: "kitchen-appliances",
    sub_category: "Wet Grinders",
    name: "Elgi Ultra Dura+ 1.25 Litre Table Top Wet Grinder with Conical Stones",
    unit: "1.25L Capacity • Patented Conical Stones • AISI 304 Stainless Steel",
    price: 7490,
    original_price: 8990,
    stock_quantity: 25,
    cashback_amount: 250,
    image_url: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.8,
    reviews_count: 1840,
    description: "Patented conical stones generate less heat while grinding for soft, fluffy idlis and crispy dosas. Rust-resistant food grade AISI 304 stainless steel drum and 10-year official warranty."
  },
  {
    id: "philips-digital-air-fryer",
    category: "Kitchen Appliances",
    category_id: "kitchen-appliances",
    sub_category: "Air Fryers",
    name: "Philips Digital Air Fryer HD9252/90 with Rapid Air Technology (4.1 Litre)",
    unit: "4.1L Capacity • 1400W • 90% Less Fat Rapid Air Tech",
    price: 6999,
    original_price: 11995,
    stock_quantity: 25,
    cashback_amount: 200,
    image_url: "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: false,
    rating: 4.7,
    reviews_count: 1920,
    description: "Fry with up to 90% less fat. Rapid Air Technology with unique starfish design creates delicious food crispy on the outside and tender on the inside. 7 preset touch screen programs."
  },

  // ==================== 9. HOME APPLIANCES ====================
  {
    id: "lg-260l-refrigerator",
    category: "Home Appliances",
    category_id: "home-appliances",
    sub_category: "Refrigerators",
    name: "LG 260 Litres 3 Star Smart Inverter Double Door Refrigerator",
    unit: "260L Double Door • Smart Inverter Compressor • Multi Air Flow",
    price: 25990,
    original_price: 33990,
    stock_quantity: 25,
    cashback_amount: 1000,
    image_url: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.8,
    reviews_count: 1420,
    description: "Energy efficient Smart Inverter Compressor with 10-year warranty, Multi Air Flow cooling vents, Toughened Glass shelves, Moist 'N' Fresh lattice box, and stabilizer-free operation."
  },
  {
    id: "samsung-8kg-washing-machine",
    category: "Home Appliances",
    category_id: "home-appliances",
    sub_category: "Washing Machines",
    name: "Samsung 8 kg 5 Star EcoBubble Fully-Automatic Front Load Washing Machine",
    unit: "8 kg Front Load • EcoBubble AI • Hygiene Steam • 1400 RPM",
    price: 34990,
    original_price: 45990,
    stock_quantity: 25,
    cashback_amount: 1500,
    image_url: "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.8,
    reviews_count: 980,
    description: "EcoBubble technology washes effectively even in cold water. AI Control personalizes cycles, Hygiene Steam removes 99.9% of bacteria and allergens, Digital Inverter with 20-year warranty."
  },

  // ==================== 10. SMART TECHNOLOGY ====================
  {
    id: "apple-watch-ultra-2-titanium",
    category: "Smart Technology",
    category_id: "smart-technology",
    sub_category: "Smartwatches",
    name: "Apple Watch Ultra 2 GPS + Cellular 49mm (Aerospace Titanium)",
    unit: "49mm / Trail Loop, 49mm / Ocean Band, 49mm / Alpine Loop",
    price: 89900,
    original_price: 94900,
    stock_quantity: 25,
    cashback_amount: 2500,
    image_url: "https://images.unsplash.com/photo-1508685096489-7aacd43bd3b1?auto=format&fit=crop&q=80&w=600",
    is_available: true,
    is_popular: true,
    rating: 4.9,
    reviews_count: 1250,
    description: "The ultimate sports and adventure watch. 49mm corrosion-resistant aerospace titanium case, precision dual-frequency GPS, up to 72 hours in Low Power Mode, 3000 nits display, and dual speakers with 86-decibel Emergency Siren."
  },
  {
    id: "apple-watch-series-10",
    category: "Smart Technology",
    category_id: "smart-technology",
    sub_category: "Smartwatches",
    name: "Apple Watch Series 10 GPS (Jet Black Aluminium, 46mm Sport Band)",
    unit: "46mm OLED • S10 SiP • ECG & Sleep Apnea • Fast Charge",
    price: 46900,
    original_price: 49900,
    stock_quantity: 25,
    cashback_amount: 1500,
    image_url: "/products/google-pixel-9.png",
    is_available: true,
    is_popular: true,
    rating: 4.9,
    reviews_count: 890,
    description: "Thinnest Apple Watch ever with our biggest display. S10 SiP, wide-angle OLED up to 40% brighter off-axis, sleep apnea notifications, depth gauge & water temperature sensor, and fast charging."
  }
];
